/**
 * CodeCraft AI - AI Idea-to-Architecture Generator
 * Synthesizes tech stacks, architectural blueprints, and starter boilerplate from natural language prompts.
 */

const BlueprintDatabase = {
  'security': {
    title: 'Autonomous Smart Contract & API Security Auditor',
    category: 'DevSecOps & Web3',
    estTime: '16-20 Hours',
    complexity: 'High (4/5)',
    stack: {
      frontend: 'Vite + React + Web Workers',
      backend: 'FastAPI + Celery Task Queue',
      aiModel: 'Gemini 3.8 Flash + DeepSeek Coder',
      database: 'PostgreSQL + Qdrant Vector DB',
      deploy: 'Cloud Run Containers (gVisor)'
    },
    pipeline: 'Code Diff Ingestion -> AST Parsing -> Static Semgrep Pass -> LLM Vulnerability Synthesis -> Proof-of-Concept Exploit Sandbox',
    boilerplate: `// Autogenerated by CodeCraft AI Studio
import { SecurityAgent, SandboxRunner } from '@codecraft/sec';

export async function runSecurityAudit(repoUrl: string) {
  console.log('🔍 Cloning & parsing AST for:', repoUrl);
  const scanner = new SecurityAgent({
    ruleset: ['OWASP-Top-10', 'Reentrancy-Guard', 'Flashloan-Resistant'],
    deepAnalysis: true
  });

  const report = await scanner.evaluateRepository(repoUrl);
  return {
    findingsCount: report.vulnerabilities.length,
    criticalScore: report.riskIndex,
    remediations: report.autoPatches
  };
}`
  },

  'video': {
    title: 'Real-Time Multimodal Video Intelligence Hub',
    category: 'AI Agents & Streaming',
    estTime: '12-16 Hours',
    complexity: 'Medium (3/5)',
    stack: {
      frontend: 'Next.js 15 + Canvas 2D + WebAudio',
      backend: 'Node.js + WebRTC SFU (LiveKit)',
      aiModel: 'Gemini Multimodal Live API',
      database: 'Redis Streams + ClickHouse',
      deploy: 'Fly.io Edge GPU Clusters'
    },
    pipeline: 'WebRTC Video Stream -> Frame Sampling (5 fps) -> Gemini Vision Tensor -> Semantic Event Extractor -> Live WebSocket Broadcast',
    boilerplate: `// Autogenerated by CodeCraft AI Studio
import { VideoStreamProcessor } from '@codecraft/multimodal';

const stream = new VideoStreamProcessor({
  fps: 10,
  resolution: '720p',
  features: ['face-landmarks', 'gesture-recognition', 'audio-sentiment']
});

stream.on('frame_insight', (insight) => {
  console.log('⚡ Real-time frame insight:', insight.summary);
});`
  },

  'default': {
    title: 'Autonomous Full-Stack Collaborative Workflow Agent',
    category: 'Autonomous Agents',
    estTime: '14-18 Hours',
    complexity: 'Medium-High (3.5/5)',
    stack: {
      frontend: 'Modern Vanilla Web (HTML5/CSS3/JS)',
      backend: 'Python 3.14 AsyncIO + gRPC',
      aiModel: 'Gemini 3.8 Flash (Thinking Model)',
      database: 'PostgreSQL + pgvector',
      deploy: 'Serverless Edge Workers'
    },
    pipeline: 'User Specification Ingestion -> Reasoning & Decomposition -> Tool Orchestration -> Dynamic Code Synthesis -> Cloud Run Edge',
    boilerplate: `# Autogenerated by CodeCraft AI Studio
import asyncio
from codecraft.pipeline import OrchestrationEngine

async def main():
    engine = OrchestrationEngine(agent_id="codecraft-core")
    print("🚀 Initializing Autonomous Hackathon Pipeline...")
    
    solution = await engine.synthesize(
        spec="Build resilient distributed cloud microservice",
        target_runtime="edge-python"
    )
    print(f"✓ Deployed successfully: {solution.endpoint}")

if __name__ == "__main__":
    asyncio.run(main())`
  }
};

function initArchitectureGenerator() {
  const inputEl = document.getElementById('gen-prompt-input');
  const generateBtn = document.getElementById('gen-submit-btn');
  const suggestionTags = document.querySelectorAll('.gen-tag-btn');
  const outputBox = document.getElementById('gen-output-box');

  const bpTitle = document.getElementById('bp-title');
  const bpCat = document.getElementById('bp-cat');
  const bpEst = document.getElementById('bp-est');
  const bpComplexity = document.getElementById('bp-complexity');
  const bpStackList = document.getElementById('bp-stack-list');
  const bpPipeline = document.getElementById('bp-pipeline');
  const bpBoilerplate = document.getElementById('bp-boilerplate-code');
  const copyBtn = document.getElementById('bp-copy-btn');
  const exportBtn = document.getElementById('bp-export-btn');

  if (!inputEl || !generateBtn || !outputBox) return;

  function generateBlueprint(query) {
    if (!query) query = 'Autonomous agent';

    generateBtn.innerHTML = `<span>⏳</span> <span>Synthesizing...</span>`;
    generateBtn.style.opacity = '0.7';
    if (typeof SoundFX !== 'undefined') SoundFX.playPulse();

    setTimeout(() => {
      let bp = BlueprintDatabase['default'];
      const qLower = query.toLowerCase();

      if (qLower.includes('secur') || qLower.includes('contract') || qLower.includes('audit') || qLower.includes('web3')) {
        bp = BlueprintDatabase['security'];
      } else if (qLower.includes('video') || qLower.includes('stream') || qLower.includes('multimodal') || qLower.includes('audio')) {
        bp = BlueprintDatabase['video'];
      }

      if (bpTitle) bpTitle.textContent = bp.title;
      if (bpCat) bpCat.textContent = bp.category;
      if (bpEst) bpEst.textContent = bp.estTime;
      if (bpComplexity) bpComplexity.textContent = bp.complexity;
      if (bpPipeline) bpPipeline.textContent = bp.pipeline;
      if (bpBoilerplate) bpBoilerplate.textContent = bp.boilerplate;

      if (bpStackList) {
        bpStackList.innerHTML = Object.entries(bp.stack).map(([k, v]) => `
          <div class="bp-card">
            <div class="bp-label">${k.toUpperCase()}</div>
            <div class="bp-val" style="font-size: 0.9rem; color: var(--primary-accent);">${v}</div>
          </div>
        `).join('');
      }

      outputBox.style.display = 'block';
      outputBox.scrollIntoView({ behavior: 'smooth', block: 'nearest' });

      generateBtn.innerHTML = `<svg width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M12 2v20M2 12h20"></path></svg> <span>Generate Blueprint</span>`;
      generateBtn.style.opacity = '1';

      if (typeof showToast !== 'undefined') {
        showToast(`✨ Blueprint synthesized for "${query.substring(0, 30)}..."`, 'success');
      }
      if (typeof SoundFX !== 'undefined') SoundFX.playSuccess();
    }, 600);
  }

  generateBtn.addEventListener('click', () => {
    generateBlueprint(inputEl.value.trim());
  });

  inputEl.addEventListener('keydown', (e) => {
    if (e.key === 'Enter') {
      generateBlueprint(inputEl.value.trim());
    }
  });

  suggestionTags.forEach(tag => {
    tag.addEventListener('click', () => {
      const text = tag.textContent.replace(/^⚡\s*/, '').trim();
      inputEl.value = text;
      generateBlueprint(text);
    });
  });

  // Copy Boilerplate Button
  if (copyBtn && bpBoilerplate) {
    copyBtn.addEventListener('click', () => {
      navigator.clipboard.writeText(bpBoilerplate.textContent).then(() => {
        copyBtn.innerHTML = `<span>✓ Copied!</span>`;
        setTimeout(() => {
          copyBtn.innerHTML = `<svg width="14" height="14" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg> <span>Copy Code</span>`;
        }, 2000);
        if (typeof showToast !== 'undefined') {
          showToast('📋 Starter boilerplate copied to clipboard!', 'success');
        }
      });
    });
  }

  // Export JSON Button
  if (exportBtn) {
    exportBtn.addEventListener('click', () => {
      const exportData = {
        title: bpTitle?.textContent,
        category: bpCat?.textContent,
        estimatedTime: bpEst?.textContent,
        complexity: bpComplexity?.textContent,
        pipeline: bpPipeline?.textContent,
        boilerplate: bpBoilerplate?.textContent,
        generatedAt: new Date().toISOString()
      };
      const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `codecraft-blueprint-${Date.now()}.json`;
      a.click();
      URL.revokeObjectURL(url);
      if (typeof showToast !== 'undefined') {
        showToast('💾 Blueprint exported as JSON file!', 'success');
      }
    });
  }

  // Initial load with default blueprint
  generateBlueprint('Autonomous Smart Contract Security Auditor');
}

document.addEventListener('DOMContentLoaded', initArchitectureGenerator);
